### ISSUE TITLE
SqlPersistenceSettings properties are not respected during script generation

### ISSUE THREAD

**Issue by dbelcham** [Particular/NServiceBus.Persistence.Sql#848] opened 2022-01-04 17:26 UTC
It's possible, and recommended in the docs, to configure your script generation using something like the following:

```
[assembly: SqlPersistenceSettings(
   MsSqlServerScripts = false,
   MySqlScripts = false,
   OracleScripts = true,
   PostgreSqlScripts = false,
   ProduceOutboxScripts = false,
   ProduceSubscriptionScripts = false,
   ProduceTimeoutScripts = false
   ProduceSagaScripts = true,
   ScriptPromotionPath = "SqlPromotionScripts")]
```
The documented expectation from the above config is that only saga scripts for Oracle will be generated. When run (v6.2.1 of SQL-P), only Oracle scripts are created (correct) but all outbox, subscription, saga and timeout scripts are created within that. The expectation is that only saga scripts would be created. 

A quick look at the code shows two things:
1) there are no tests verifying that these configs are working
2) the `Produce*` settings are defaulted to `true` while the database dialect settings are not.

**Comment by danielmarbach** [comment] 2022-01-05 10:49
@dbelcham Thanks for pointing this behavior out. We are currently triaging the issue further and will report back as soon as that is done.

**Comment by danielmarbach** [comment] 2022-01-05 12:08
We have reviewed your issue and added it to our backlog. It is eligible to be picked up for a future release, but we cannot provide a firm timeline.

**Comment by danielmarbach** [comment] 2022-05-05 12:00
@dbelcham @timbussmann and I have independently tried to reproduce this problem both with a sample and with a unit and integration test, and somehow we couldn't. There are plenty of tests that verify the correct behavior of the metadata that is being read, as well as the default values that might get assigned to the script generation. 

Could it be that it was some kind of a left over from a previous compilation? It seems we are potentially missing something in the reproduction steps. Do you have ideas how we could reproduce the issue you have been seeing?

**Comment by mortenn** [comment] 2022-05-05 12:10
I am certainly seeing an issue with this attribute in 6.2.1:
![image](https://user-images.githubusercontent.com/640095/166919860-02a4aae7-acf3-42b6-9133-2fa1ecc5c45b.png)

**Comment by timbussmann** [comment] 2022-05-06 07:12
@mortenn apology for the dumb question but the screenshot seems to show files from ~4 months ago, are you sure these files are recreated when you delete them? Are you able to share a simple repro sample with us?

**Comment by mortenn** [comment] 2022-05-06 16:45
I deleted them and rebuilt and they reappeared.
I did find it a little curious that the timestamp was dated in january, but I didn't really look into it any deeper.

I've seen the files be created for other solutions on a build server where the entire work folder was created fresh, though.

**Comment by markgould** [comment] 2022-05-25 16:49
I'm seeing this too when I'm specifying "[assembly: SqlPersistenceSettings(MsSqlServerScripts = true)]" at the assembly level. An old issue used to be that you had to be sure to reference NServiceBus.Persistence.SQL directly for it to find and use the attribute.

**Comment by markgould** [comment] 2022-05-25 17:33
running "sql-persistence script .\AssemblyName.dll -v" correctly creates the scripts for the MsSql only

Building from VS results in all folders being created. This makes me think the script task is failing to find the attribute. This project happens to be one that is hosted in an ASP.Net core project. 

I wonder if it has anything to do with the project SDK?

**Comment by timbussmann** [comment] 2022-05-27 14:37
> Building from VS results in all folders being created. This makes me think the script task is failing to find the attribute. This project happens to be one that is hosted in an ASP.Net core project.

can you observe the same behavior @mortenn ?

**Comment by mortenn** [comment] 2022-06-08 20:45
As I recall, that is what I was observing a long time ago when I started following this issue.
At this time I am working for a different customer, so I do not have the ability to double check right now, but I can try to get to it some time soon.
Reproducing this shouldn't be that complicated, though?

**Comment by dbelcham** [comment] 2022-12-29 02:11
I haven't worked with the client I saw this on for quite a while, but I just added this to a personal project and see the exact same results as I was seeing before. The `bin\Debug\net6.0\NServiceBus.Persistence.Sql` folder was deleted prior to running a build in VS using `Ctrl+B`. All of what is shown in the images below appeared as part of the build run.

This was a project that I transitioned from the LearningPersistence to SqlPersistence and this behaviour appeared the very first time I ran the build. The transition included adding the nuget package and the `[assembly: ...` attribute in the `Program.cs` file.

![image](https://user-images.githubusercontent.com/1378057/209893991-995e7689-b0c7-4bd2-836b-a0eebdc6a4be.png)
![image](https://user-images.githubusercontent.com/1378057/209894007-38799785-07db-4ac4-99ca-2149fb115753.png)
![image](https://user-images.githubusercontent.com/1378057/209894026-3ccf1dc5-b3b6-4afd-9b28-b257b6c74208.png)
![image](https://user-images.githubusercontent.com/1378057/209894042-fe047762-e973-47b3-96c5-4a86d6ced241.png)

**Comment by mikeminutillo** [comment] 2022-12-30 03:31
I may have been able to replicate this. What I can see is that we do not correctly clean up the scripts in the `obj` folder. So once we have generated a script once, it never goes away.

@dbelcham can you check and see if you have the scripts in your `obj\Debug\net6.0\NServiceBus.Persistence.Sql` folder? If you delete them and rebuild, do they stay gone?

When we purge the scripts previously generated we [intend to only do it for the selected dialects](https://github.com/Particular/NServiceBus.Persistence.Sql/blob/master/src/ScriptBuilder/ScriptGenerator.cs#L107). Unfortunately [that logic](https://github.com/Particular/NServiceBus.Persistence.Sql/blob/master/src/ScriptBuilder/ScriptGenerator.cs#L130-L133) is broken [here](https://github.com/Particular/NServiceBus.Persistence.Sql/commit/04999bcd14759a003d1071361477000fec6abbcd). It used to be that not providing a dialect meant we assumed all of them. Since that change, that's no longer true. If this is the root cause, it's an easy fix.

**Closed** 2023-01-19 11:41 UTC
Labels: Bug, Triaged
